### ISSUE TITLE
TFGuilds TODO (8/10)

### ISSUE THREAD

**Issue by ghost** [TotalFreedomMC/TFGuilds#1]
# Main priorities
- [x] Add guild chat spy for admins
- [x] Tab auto completion for certain commands
- [x] Add `%rank%` for guild tags; displaying guild ranks in tags
- [x] Add default guild ranks (For every new member, give them said default rank)
- [ ] Page guilds in /g list, make it 10 guilds per page

### Other (not as important, anyone can work on these)
